Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
entrada = list(range(1, 1_000))
classical_speedup = np.linspace(10, 30, 10)

px.line(
    {
        "Tempo": np.array(
            [
                [*np.array(entrada), *np.array(list(map(np.sqrt, entrada))) * speedup]
                for speedup in classical_speedup
            ]
        ).flatten(),
        "Tamanho da Entrada": np.array(
            [[*entrada, *entrada] for _ in classical_speedup]
        ).flatten(),
        "Modelo de Computa√ß√£o": np.array(
            [
                [
                    *["Cl√°ssico"] * len(entrada),
                    *["Qu√¢ntico"] * len(entrada),
                ]
                for _ in classical_speedup
            ]
        ).flatten(),
        "Speedup Cl√°ssico": np.array(
            [
                [*[speedup] * len(entrada), *[speedup] * len(entrada)]
                for speedup in classical_speedup
            ]
        ).flatten(),
    },
    x="Tamanho da Entrada",
    y="Tempo",
    color="Modelo de Computa√ß√£o",
    animation_frame="Speedup Cl√°ssico",
    title=f"Tempo de Computa√ß√£o Cl√°ssico vs. Qu√¢ntico.",
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m entrada [38;5;241m=[39m [38;5;28mlist[39m([38;5;28mrange[39m([38;5;241m1[39m, [38;5;241m1_000[39m))
[0;32m----> 2[0m classical_speedup [38;5;241m=[39m [43mnp[49m[38;5;241m.[39mlinspace([38;5;241m10[39m, [38;5;241m30[39m, [38;5;241m10[39m)
[1;32m      4[0m px[38;5;241m.[39mline(
[1;32m      5[0m     {
[1;32m      6[0m         [38;5;124m"[39m[38;5;124mTempo[39m[38;5;124m"[39m: np[38;5;241m.[39marray(
[0;32m   (...)[0m
[1;32m     35[0m     title[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;124mTempo de Computa√ß√£o Cl√°ssico vs. Qu√¢ntico.[39m[38;5;124m"[39m,
[1;32m     36[0m )

[0;31mNameError[0m: name 'np' is not defined

